name: sing-box global proxy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 安装 sing-box（.deb）
      - name: Install sing-box
        run: |
          URL=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest  |  jq -r '.assets[] | select(.name | test("^sing-box_.*_linux_amd64\\.deb$"))  | .browser_download_url')
          echo "URL=$URL"

          wget -O sing-box-linux-amd64.deb "$URL"

          sudo dpkg -i sing-box-linux-amd64.deb

      # 启动 sing-box（⚠️ 不用 systemctl）
      - name: Start sing-box
        run: |
          nohup sing-box run -c config.json > /tmp/sb.log 2>&1 &
          sleep 5
          curl ipinfo.io

      # - name: Enable proxy
      #   run: |
      #     echo "http_proxy=http://127.0.0.1:7890" >> $GITHUB_ENV
      #     echo "https_proxy=http://127.0.0.1:7890" >> $GITHUB_ENV
      #     echo "all_proxy=socks5://127.0.0.1:7890" >> $GITHUB_ENV

      # 测试
      - name: Test proxy
        run: |
          curl ipinfo.io
          curl -x http://127.0.0.1:7890 ipinfo.io