name: Test Proxy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download sing-box
        run: |
          URL=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest  |  jq -r '.assets[] | select(.name | test("^sing-box-.*-linux-amd64\\.tar\\.gz$"))  | .browser_download_url')
          echo "URL=$URL"

          wget -O sing-box-linux-amd64.tar.gz "$URL"
          tar -xvf sing-box-linux-amd64.tar.gz
          mv sing-box*/sing-box ./sing-box
          chmod +x sing-box

      - name: Write config
        run: |
          cat > config.json << 'EOF'
          {
            "log": { "level": "info" },
            "inbounds": [
              {
                "type": "mixed",
                "listen": "127.0.0.1",
                "listen_port": 7890
              }
            ],
            "outbounds": [
              {
                "type": "vless",
                "server": "104.19.69.45",
                "server_port": 8443,
                "uuid": "01d1730d-e5e8-474a-8ffe-d80106c877a8",
                "tls": {
                  "enabled": true,
                  "server_name": "wpg.zxs.us.kg"
                },
                "transport": {
                  "type": "ws",
                  "path": "/?ed=2560",
                  "headers": {
                    "Host": "wpg.zxs.us.kg"
                  }
                }
              }
            ]
          }
          EOF

      - name: Start sing-box
        run: |
          nohup ./sing-box run -c config.json > sb.log 2>&1 &
          sleep 5

      - name: Test proxy
        run: |
          curl -x http://127.0.0.1:7890 https://www.google.com -I
          curl ipinfo.io